// Every spoken line in the game, in English.
//   "line.id": ["who", "What they say."]
// Scripts refer to lines by ID only. A voice recording for a line is a sound file
// named after its ID (see js/content/sound.js). A translation is a copy of this
// file with the same IDs.
//
// PLACEHOLDER CONTENT below, written to prove the engine. All of it is original.
// docs/CHARACTERS.md says how each of these people talks. Two rules from it:
//   a line belongs to one person (if anybody could have said it, rewrite it), and
//   every fact Big Sister states is true (docs/CHARACTERS.md lists them, and which have been checked).

export const lines = {
  // ---------- intro movie ----------
  "intro.1": ["son", "Dad, the map says this road ends. There's just a little drawing of a shrug."],
  "intro.2": ["dad", "Maps don't know about shortcuts."],
  "intro.3": ["son", "Dad. DAD. The sky is doing the thing my slushie does."],
  "intro.4": ["dad", "Weather. Probably."],
  "intro.5": ["son", "Are we when yet?"],
  "intro.6": ["dad", "No, but we're making good time."],

  // ---------- Egypt: Dad ----------
  "egypt.arrive.1": ["dad", "Okay. Nobody panic. The car has landed."],
  "egypt.arrive.2": ["dad", "Buddy? ... Buddy?"],
  "egypt.arrive.3": ["dad", "He was in the passenger seat a minute ago. Or a thousand years from now. I'm still working out the tenses."],
  "egypt.wagon.look": ["dad", "Two hundred thousand miles and she still runs. Not right now. But in general."],
  "egypt.wagon.use": ["dad", "There's a road map in the glovebox. Three states, zero centuries."],
  "egypt.wagon.empty": ["dad", "Nothing left in there but ketchup packets. I'm saving those."],
  "egypt.river.look": ["dad", "Either that's the Nile or a very committed car wash."],
  "egypt.reeds.look": ["dad", "Reeds. Nature's ballpoint."],
  "egypt.reeds.take": ["dad", "One reed. I'll bring it back. That's a lie. I never bring pens back."],
  "egypt.reeds.again": ["dad", "One is plenty. I'm not opening a stationery shop."],
  "egypt.pyramids.look": ["dad", "They look brand new. Somebody kept the receipt."],
  "egypt.scribe.look": ["dad", "He's been staring at a blank sheet for a while. I know writer's block when I see it."],
  "egypt.scribe.hello": ["scribe", "You fell out of the sky in a red chariot with no horses."],
  "egypt.scribe.hello2": ["dad", "It has a hundred and forty horses. They're resting."],
  "egypt.ask.boy": ["dad", "Have you seen a boy? About this tall, asks a lot of questions?"],
  "egypt.ans.boy": ["scribe", "A small one fell from the sky before you did. The humming door took him away again."],
  "egypt.ans.boy2": ["scribe", "I would write down where it went. But my pen is at the bottom of the river."],
  "egypt.ask.door": ["dad", "What is the humming door?"],
  "egypt.ans.door": ["scribe", "It opens by the water. It closes when you look at it too hopefully."],
  "egypt.ask.bye": ["dad", "I'll let you get back to your sheet."],
  "egypt.ans.bye": ["scribe", "It is not going anywhere. Neither am I."],
  "egypt.give.reed": ["dad", "Here. It's a pen. Some assembly required."],
  "egypt.got.reed": ["scribe", "A good reed. You have the eye of a scribe and the clothes of a market stall."],
  "egypt.need.sheet": ["scribe", "Now I need something to draw the door's path on. This sheet is for taxes."],
  "egypt.give.map": ["dad", "Draw on this. It's a map. It's already wrong, you can't make it worse."],
  "egypt.got.map.nopen": ["scribe", "A fine sheet. I have nothing to mark it with."],
  "egypt.got.map": ["scribe", "There. The door opens here, then here, then here. It likes a schedule."],
  "egypt.door.steady": ["scribe", "Stand where I have marked and it will hold still for you."],
  "egypt.hole.look": ["dad", "A hole in the air the size of a dinner plate. I am not the size of a dinner plate."],
  "egypt.hole.small": ["dad", "It shrinks every time I get close. I have the same effect on waiters."],
  "egypt.hole.big": ["dad", "Now that's a door."],
  "egypt.hole.go": ["dad", "Hold on, buddy. Dad's taking the next shortcut."],
  "egypt.hole.wait": ["dad", "Not until I know where it comes out. I've made that mistake once today."],

  // ---------- Rome: the Son. Every line of his swerves. ----------
  "rome.arrive.1": ["son", "Dad? ... This is NOT the rest stop. The rest stop had a vending machine."],
  "rome.arrive.2": ["son", "Everyone here is wearing a bedsheet. Ten out of ten. Biggest sleepover in history."],
  "rome.arrive.3": ["son", "Okay. Operation Find Dad. Step one: snacks. Step two: also Dad."],
  "rome.temple.look": ["son", "Giant stripy pillars. Dad would say they're holding up well. Seven out of ten. Would climb."],
  "rome.fountain.look": ["son", "There's money at the bottom. People throw coins in the water here. On PURPOSE. I love this place."],
  "rome.fountain.take": ["son", "Operation Borrow-A-Wish is GO. Splish."],
  "rome.fountain.again": ["son", "One wish is borrowing. Two is a crime spree."],
  "rome.hole.look": ["son", "It hums. Dad says it's the wind. Dad says EVERYTHING is the wind. I have a list."],
  "rome.hole.use": ["son", "I'm not jumping in there again without a snack. That's a rule I made up just now and I stand by it."],
  "rome.hole.coin": ["son", "Heads, I find Dad. Tails, Dad finds me. Edge, we get a dog."],
  "rome.hole.coin2": ["son", "... It didn't come back down. Does that count as edge? Do we get the dog?"],

  // ---------- home, that evening: Mom, Big Sister, Little Sister ----------
  "home.arrive.vm1": ["dad", "'You've reached Dad. I can't pick up right now. I'm either driving or lost.'"],
  "home.arrive.vm2": ["dad", "'And I am never lost. So: driving. Leave a message.'"],
  "home.arrive.1": ["mom", "Voicemail. That is the ninth time. I had decided to stop worrying at eight."],
  "home.arrive.2": ["lilsis", "Daddy's not lost. Daddy's EARLY."],
  "home.arrive.2b": ["bigsis", "That is not what early means."],
  "home.arrive.3": ["bigsis", "They left at noon. It is a four-hour drive. It is now nine forty. For the record, that is not a shortcut."],
  "home.arrive.4": ["mom", "Dinner was at six. I set five places, and I am not clearing two of them away."],
  "home.arrive.5": ["bigsis", "His phone still tells the family computer where it is. Dad set that up himself. He called it 'the mainframe'."],
  "home.arrive.6": ["lilsis", "Then the computer KNOWS! Ask the computer!"],
  "home.arrive.7": ["mom", "Then that is where we begin, girls. We are going to find out where that phone was last seen."],

  "home.pc.look.mom": ["mom", "The family computer. Your father calls it 'the mainframe'. It is nine years old and it sighs when you switch it on."],
  "home.pc.look.bigsis": ["bigsis", "Our computer. It runs the family map. It also runs. Technically."],
  "home.pc.look.lilsis": ["lilsis", "The computer! It has a game where a cat eats numbers."],
  "home.pc.offline.mom": ["mom", "'No internet.' I see. It was working perfectly well until your father improved it."],
  "home.pc.offline.bigsis": ["bigsis", "No connection. Fun fact: the first message ever sent on the network that became the internet was 'LO'. They were typing LOGIN, and it crashed. October 1969."],
  "home.pc.offline.bigsis2": ["bigsis", "So this is traditional."],
  "home.pc.offline.lilsis": ["lilsis", "It says NO. Computers aren't allowed to say no. I'm telling Mommy."],
  "home.pc.router": ["mom", "The router lives in the closet under the stairs. Your father keeps the internet next to the vacuum cleaner."],
  "home.pc.login.mom": ["mom", "It wants a password. Four numbers. 'Forgot it? Ask Dad.' I would dearly love to."],
  "home.pc.login.bigsis": ["bigsis", "Four digits. Ten thousand possibilities. Dad will have written it down somewhere. He always does."],
  "home.pc.login.lilsis": ["lilsis", "One, two, three, four! ... It said no AGAIN."],
  "home.pc.type.mom": ["mom", "One. Nine. Two. Eight."],
  "home.pc.type.bigsis": ["bigsis", "One, nine, two, eight. I type with all ten fingers. It is not difficult."],
  "home.pc.type.lilsis": ["lilsis", "One! Nine! Two! Eight! I typed it with ONE finger."],
  "home.pc.question.mom": ["mom", "'What did you promise on your wedding day?' Oh, my love. You would."],
  "home.pc.question.bigsis": ["bigsis", "'What did you promise on your wedding day?' I was not invited to the wedding. Mother?"],
  "home.pc.question.lilsis": ["lilsis", "It's asking about a wedding. I wasn't BORN. Mommy!"],
  "home.pc.pick.love": ["mom", "To love, honor and cherish."],
  "home.pc.pick.scenic": ["mom", "To always take the scenic route."],
  "home.pc.pick.directions": ["mom", "To never ask for directions."],
  "home.pc.wrong.love": ["mom", "No? I did say that. I had hoped he was listening."],
  "home.pc.wrong.scenic": ["mom", "No. That was not a promise. That was a warning."],
  "home.pc.right": ["mom", "He promised me he would never ask for directions. It is the one promise he has always kept."],
  "home.pc.map.1": ["mom", "There. 'Dad's phone. Last seen 5:47 p.m. Thirty-seven miles past Last Gas.' In the middle of Nevada."],
  "home.pc.map.2": ["bigsis", "That is not on the way home. That is not on the way to anywhere."],
  "home.pc.map.3": ["lilsis", "Is Nevada past the mailbox?"],
  "home.pc.map.4": ["mom", "A little past the mailbox, darling. Shoes on, both of you. We leave tonight."],
  "home.pc.done.mom": ["mom", "One dot, in the middle of nothing. I have looked at it quite long enough."],
  "home.pc.done.bigsis": ["bigsis", "Thirty-seven miles past Last Gas. I have memorized it. I memorize everything."],
  "home.pc.done.lilsis": ["lilsis", "The dot is Daddy. Hi, dot."],

  "home.note.look.mom": ["mom", "Your father's handwriting. 'Password: the year of the best thing since.' Since WHAT, my love? He has left off the end."],
  "home.note.look.lilsis": ["lilsis", "It says 'PASS WORD'. And then more words. Daddy does the loopy Ys."],
  "home.note.take.mom": ["mom", "I will hold on to this. It is the nearest thing to your father in the house."],
  "home.note.take.lilsis": ["lilsis", "MINE. I mean: evidence."],
  "home.note.solve.1": ["bigsis", "'Password: the year of the best thing since.' ...Since sliced bread. With Dad, everything is the best thing since sliced bread."],
  "home.note.solve.2": ["bigsis", "Fun fact: sliced bread was first sold on the seventh of July, 1928, in Chillicothe, Missouri."],
  "home.note.solve.3": ["bigsis", "The password is 1928. Dad, that is so... actually, that is quite good."],

  "home.closet.look.mom": ["mom", "The closet under the stairs. Something has fallen against the door from inside. It opens exactly this far."],
  "home.closet.look.bigsis": ["bigsis", "The door opens four inches. I am wider than four inches. I have shoulders."],
  "home.closet.look.lilsis": ["lilsis", "It's dark in there. And there's a tiny light! That's the internet. The internet is TINY."],
  "home.closet.use.mom": ["mom", "A lady does not squeeze into closets, darling. A lady has a seven-year-old."],
  "home.closet.use.bigsis": ["bigsis", "I refuse. There are spiders in there, and I am thirteen. Both of those are final."],
  "home.closet.go.1": ["lilsis", "I FIT!"],
  "home.closet.go.2": ["lilsis", "It's SO dark. There's the vacuum. And Daddy's golf sticks. And a plug that isn't plugged into anything!"],
  "home.closet.go.3": ["mom", "Into the wall, sweetheart. The socket with two little eyes and a surprised mouth."],
  "home.closet.go.4": ["lilsis", "The red light went GREEN! I fixed the internet! I'm a ENGINEER!"],
  "home.closet.go.5": ["bigsis", "AN engineer."],
  "home.closet.go.6": ["lilsis", "That's what I SAID."],
  "home.closet.again": ["lilsis", "I already fixed it. It's green. Green means I'm good at it."],
  "home.closet.done.mom": ["mom", "A small green light. Clever girl."],
  "home.closet.done.bigsis": ["bigsis", "The light is green. She will be insufferable for a week."],

  "home.piano.look.mom": ["mom", "Your sister's piano. The one thing in this house that is always in tune."],
  "home.piano.look.bigsis": ["bigsis", "My piano. Fun fact: Bartolomeo Cristofori built the first one, in Florence, around the year 1700."],
  "home.piano.look.bigsis2": ["bigsis", "They called it a harpsichord with soft and loud. I would have called it a miracle."],
  "home.piano.look.lilsis": ["lilsis", "The piano. I know one song. It's the one with two fingers."],
  "home.piano.use.mom": ["mom", "Not tonight. Tonight I would only play something sad, and play it badly."],
  "home.piano.use.bigsis": ["bigsis", "Something in a minor key. It felt appropriate."],
  "home.piano.use.bigsis2": ["bigsis", "When Dad is home I will play the loud one he likes. Twice."],
  "home.piano.use.lilsis": ["lilsis", "PLONK. That was my song. It's called 'Plonk'."],

  "home.books.mom": ["mom", "Your sister's novels and your father's manuals. The novels have been finished."],
  "home.books.bigsis": ["bigsis", "My books. Alphabetical by author, and then by how much I cried."],
  "home.books.lilsis": ["lilsis", "Too many words. I like the one about the duck. The duck has NO words."],
  "home.photo.mom": ["mom", "The five of us at the lake. Your father took a shortcut that day, too. We saw a great deal of the lake."],
  "home.photo.bigsis": ["bigsis", "Five people, one tripod. Dad set the timer and ran. He is the blur."],
  "home.photo.lilsis": ["lilsis", "That's me! I was SIX. I'm way bigger now. Almost."],
  "home.table.mom": ["mom", "Roast chicken at six o'clock sharp. It is no longer sharp."],
  "home.table.bigsis": ["bigsis", "'The table,' she observed, 'was set for five. The house was not.'"],
  "home.table.lilsis": ["lilsis", "Can I have Daddy's potatoes? He's not using them."],
  "home.chair.mom": ["mom", "Your father's chair. It has kept his shape. I find I rather like that tonight."],
  "home.chair.bigsis": ["bigsis", "Dad's chair. His crossword is on the arm. Seven across is wrong. I haven't told him."],
  "home.chair.lilsis": ["lilsis", "Daddy's chair. If you sit in it you have to say 'well, well, well'."],
  "home.window.mom": ["mom", "No headlights. I have looked eleven times. Twelve."],
  "home.window.bigsis": ["bigsis", "'The street,' she wrote, 'was the wrong kind of quiet.' ...That's good. I'm keeping that."],
  "home.window.lilsis": ["lilsis", "I'm watching for the car. I'm the best at watching. I haven't blinked since dinner."],
  "home.stairs.mom": ["mom", "Nobody is going up to bed tonight. Least of all me."],
  "home.stairs.bigsis": ["bigsis", "Thirteen steps. Yes, I counted. I count in fours when I'm nervous, and thirteen doesn't divide."],
  "home.stairs.lilsis": ["lilsis", "I'm not tired. I'm NEVER tired. ...What time is it?"],
  "home.door.early.mom": ["mom", "Not until we know where we are going. One of us in this family must."],
  "home.door.early.bigsis": ["bigsis", "We don't have a destination. A journey without a destination is just Dad."],
  "home.door.early.lilsis": ["lilsis", "I'm not allowed out after dark. Unless it's a 'mergency. Is it a 'mergency?"],
  "home.leave.1": ["mom", "Coats, girls. We are going to Nevada."],
  "home.leave.2": ["bigsis", "I'll bring the atlas. And a book. And a second book, in case the first one ends."],
  "home.leave.3": ["lilsis", "I'll bring my boots! I'm already WEARING my boots!"],
  "home.leave.4": ["mom", "We are going to be perfectly polite, and completely impossible to get rid of."],

  "home.talk.mom.bigsis.1a": ["mom", "You are very quiet, darling."],
  "home.talk.mom.bigsis.1b": ["bigsis", "I am thinking. It only looks like quiet from the outside."],
  "home.talk.mom.bigsis.2a": ["mom", "Whatever has happened, we will deal with it the way we deal with everything."],
  "home.talk.mom.bigsis.2b": ["bigsis", "With a list?"],
  "home.talk.mom.bigsis.2c": ["mom", "With a list."],
  "home.talk.mom.lilsis.1a": ["mom", "Are you frightened, sweetheart?"],
  "home.talk.mom.lilsis.1b": ["lilsis", "No! ...Are YOU?"],
  "home.talk.mom.lilsis.1c": ["mom", "Not while I have you to look after me."],
  "home.talk.mom.lilsis.2a": ["lilsis", "Mommy, why did Daddy take a shortcut?"],
  "home.talk.mom.lilsis.2b": ["mom", "Because the long way around has never once been his idea."],
  "home.talk.bigsis.mom.1a": ["bigsis", "Mom. Statistically, they are fine."],
  "home.talk.bigsis.mom.1b": ["mom", "Thank you, darling. And unstatistically?"],
  "home.talk.bigsis.mom.1c": ["bigsis", "...Also fine. Probably."],
  "home.talk.bigsis.mom.2a": ["bigsis", "I've started a new chapter. It is called 'The Night They Didn't Come Home'."],
  "home.talk.bigsis.mom.2b": ["mom", "Do give it a happy ending."],
  "home.talk.bigsis.lilsis.1a": ["bigsis", "Don't touch anything while I'm thinking."],
  "home.talk.bigsis.lilsis.1b": ["lilsis", "I'm not touching. I'm HOLDING."],
  "home.talk.bigsis.lilsis.2a": ["lilsis", "Why do you know so many years?"],
  "home.talk.bigsis.lilsis.2b": ["bigsis", "Because somebody has to. Years don't remember themselves."],
  "home.talk.lilsis.mom.1a": ["lilsis", "Mommy, I can help. I'm small but I'm MIGHTY."],
  "home.talk.lilsis.mom.1b": ["mom", "You are the mightiest person I know, my love. Do aim it carefully."],
  "home.talk.lilsis.mom.2a": ["lilsis", "Can I stay up?"],
  "home.talk.lilsis.mom.2b": ["mom", "Tonight, yes."],
  "home.talk.lilsis.mom.2c": ["lilsis", "...Now I'm worried."],
  "home.talk.lilsis.bigsis.1a": ["lilsis", "Read me a fact."],
  "home.talk.lilsis.bigsis.1b": ["bigsis", "It's 'tell me a fact'."],
  "home.talk.lilsis.bigsis.1c": ["lilsis", "Tell me a READ."],
  "home.talk.lilsis.bigsis.2a": ["lilsis", "My tooth is loose. Look. LOOK."],
  "home.talk.lilsis.bigsis.2b": ["bigsis", "I have seen the tooth. Everyone on this street has seen the tooth."],

  // ---------- the middle of Nevada, the next morning ----------
  "nevada.arrive.1": ["mom", "Thirty-seven miles past Last Gas. This is where the map stops."],
  "nevada.arrive.2": ["bigsis", "Fun fact: Nevada became a state on the thirty-first of October, 1864. Halloween."],
  "nevada.arrive.3": ["lilsis", "It's all DIRT. Who ordered this much dirt?"],
  "nevada.arrive.4": ["mom", "Somebody here saw something. We will ask nicely. Stay where I can see you, girls."],

  "nevada.old.look.mom": ["mom", "A gentleman in a lawn chair, selling rocks and lemonade to a road with no cars on it. He will have seen whatever passed."],
  "nevada.old.look.bigsis": ["bigsis", "One witness. Elderly, seated, hat. He is pretending not to watch us. Badly."],
  "nevada.old.look.lilsis": ["lilsis", "He's got a white beard like a wizard. A wizard who sells ROCKS."],
  "nevada.old.lilsis.1": ["lilsis", "Mister, did you see my daddy? He's tall and he has a moustache and he's EARLY."],
  "nevada.old.lilsis.2": ["oldtimer", "Lemonade's a dollar, little miss. Stories are extra."],
  "nevada.old.lilsis.3": ["lilsis", "I don't HAVE a dollar. I have a tooth."],
  "nevada.old.bigsis.1": ["bigsis", "Sir. Did you observe a red station wagon yesterday at approximately 5:47 p.m.?"],
  "nevada.old.bigsis.2": ["oldtimer", "Didn't see nothing. Been not seeing nothing out here for forty years."],
  "nevada.old.bigsis.3": ["bigsis", "That is a double negative. Technically, you saw something."],
  "nevada.old.bigsis.4": ["oldtimer", "Technically, I'm closed."],
  "nevada.old.mom.1": ["mom", "Good morning. Forgive us for troubling you. May I buy three lemonades, and a few minutes of your time?"],
  "nevada.old.mom.2": ["oldtimer", "Well, now. Forty years out here, and you're the first one to say good morning."],
  "nevada.old.mom.3": ["oldtimer", "Folks come asking about yesterday. Men in gray suits, mostly. I tell 'em I didn't see nothing."],
  "nevada.old.mom.4": ["mom", "And did you see nothing?"],
  "nevada.old.mom.5": ["oldtimer", "Depends who's asking. You kin to whoever was in that car?"],
  "nevada.old.mom.6": ["mom", "My husband and my son."],
  "nevada.old.mom.7": ["oldtimer", "Then tell me what they were driving. The gray suits couldn't."],
  "nevada.car.wagon": ["mom", "A red station wagon with wood on the sides and far too much luggage on the roof."],
  "nevada.car.sedan": ["mom", "A sensible silver sedan."],
  "nevada.car.black": ["mom", "A black car with dark windows."],
  "nevada.car.no.sedan": ["oldtimer", "No, ma'am. Nothing sensible came down this road yesterday."],
  "nevada.car.no.black": ["oldtimer", "That's what the gray suits drive. Try again."],
  "nevada.old.again": ["oldtimer", "Still want to know what they were driving, ma'am."],
  "nevada.old.saw.1": ["oldtimer", "That's the one. Red wagon, wood trim, cooler on the roof. Driver waved at me. Nobody waves anymore."],
  "nevada.old.saw.2": ["oldtimer", "Then the sky opened up like a tin can. The road sign changed its mind. And that wagon drove straight in."],
  "nevada.old.saw.3": ["oldtimer", "Hour later the gray suits came and put up a fence. 'Radiation,' they say. Third piece of desert they've shut this year."],
  "nevada.old.saw.4": ["mom", "Thank you. You have been kinder than you needed to be."],
  "nevada.old.saw.5": ["oldtimer", "One more thing. This fell out of the sky this morning. Hit my hat. Seems like it's yours more than mine."],
  "nevada.old.saw.6": ["mom", "A silver coin. With a very serious gentleman on it."],
  "nevada.ask.fence": ["mom", "What is behind the fence?"],
  "nevada.ans.fence": ["oldtimer", "Used to be nothing. Now it's nothing with a fence around it."],
  "nevada.ask.areas": ["mom", "You said they have closed other places."],
  "nevada.ans.areas": ["oldtimer", "Three this year. Always the same sign. 'Elevated radiation.' Funny thing is, my old Geiger counter never clicks once."],
  "nevada.ask.bye": ["mom", "We must not keep you."],
  "nevada.ans.bye": ["oldtimer", "You ain't. I got all day. I got all decade."],
  "nevada.old.after.lilsis.1": ["oldtimer", "Your ma's good people. Lemonade's on the house, little miss."],
  "nevada.old.after.lilsis.2": ["lilsis", "On the house? WHERE'S the house?"],
  "nevada.old.after.bigsis.1": ["bigsis", "Sir. They say radiation. Do you own anything that measures it?"],
  "nevada.old.after.bigsis.2": ["oldtimer", "My daddy's Geiger counter. Clicked fine for him in fifty-seven. Hasn't clicked once this year."],
  "nevada.old.after.bigsis.3": ["bigsis", "Then somebody is lying, and it isn't the Geiger counter. Interesting."],
  "nevada.old.coin": ["mom", "He gave it to us, darling. It would be rude to give it back."],

  "nevada.agent.look.mom": ["mom", "A man in a gray suit, standing precisely in front of the one thing worth reading."],
  "nevada.agent.look.bigsis": ["bigsis", "Gray suit, gray tie, dark glasses. He is standing in front of that notice on purpose. That is called obstruction."],
  "nevada.agent.look.lilsis": ["lilsis", "He's ALL gray. Is his dog gray?"],
  "nevada.agent.mom.1": ["mom", "Good morning. May we read the notice behind you?"],
  "nevada.agent.mom.2": ["agent", "There is no notice, ma'am."],
  "nevada.agent.mom.3": ["mom", "I can see the corner of it."],
  "nevada.agent.mom.4": ["agent", "I can neither confirm nor deny a corner."],
  "nevada.agent.bigsis.1": ["bigsis", "Under what authority is this area closed?"],
  "nevada.agent.bigsis.2": ["agent", "I can neither confirm nor deny that it is an area."],
  "nevada.agent.bigsis.3": ["bigsis", "It has a fence."],
  "nevada.agent.bigsis.4": ["agent", "I can neither confirm nor deny the fence."],
  "nevada.agent.lil.1": ["lilsis", "Why is your tie gray?"],
  "nevada.agent.lil.2": ["agent", "Move along, little girl."],
  "nevada.agent.lil.3": ["lilsis", "Is your car gray? Is your DOG gray? Do you have a dog?"],
  "nevada.agent.lil.4": ["agent", "I can neither confirm nor deny a dog."],
  "nevada.agent.lil.5": ["lilsis", "What's his NAME? Why are you standing there? Is it your turn? Who had the turn before you? Do you get a snack?"],
  "nevada.agent.lil.6": ["agent", "...Sir? It's me. I have a situation. No, sir. She is about seven."],
  "nevada.agent.lil.7": ["lilsis", "Who are you talking to? Is it your mommy? Can I say hi?"],
  "nevada.agent.lil.8": ["bigsis", "'It was,' she noted, 'the finest interrogation she had ever witnessed.'"],
  "nevada.agent.busy": ["agent", "Sir, now she wants to know whose side the SUN is on. ...No, sir. I didn't have an answer either."],
  "nevada.agent.again.1": ["lilsis", "Why is the sky? Not why is it BLUE. Why IS it?"],
  "nevada.agent.again.2": ["agent", "...We are going to need a bigger department."],

  "nevada.notice.blocked.mom": ["mom", "The gentleman is standing exactly in front of it. One admires the precision."],
  "nevada.notice.blocked.bigsis": ["bigsis", "I can read 'CLO' and half a 'D'. That is not enough to work with."],
  "nevada.notice.blocked.lilsis": ["lilsis", "The gray man is in the WAY. I could ask him to move. I could ask him a LOT of things."],
  "nevada.notice.mom.1": ["mom", "'Area closed. Elevated radiation levels. Sectors 44 and 1250 sealed until further notice.'"],
  "nevada.notice.mom.2": ["mom", "Sectors. As though the desert had been numbered. Your sister should see this."],
  "nevada.notice.lilsis": ["lilsis", "It says... A, R, E, A. And a yellow spinny flower. 'Radiator levels.' That's BAD, right?"],
  "nevada.notice.big.1": ["bigsis", "'Elevated radiation levels.' In Nevada, people will believe that. Fun fact: atomic bombs were tested out here from 1951 until 1992."],
  "nevada.notice.big.2": ["bigsis", "Which makes it a very good excuse. But look at the sectors. Forty-four. Twelve-fifty."],
  "nevada.notice.big.3": ["bigsis", "Nobody numbers sectors like that. Those aren't places, Mother. I think those are years."],
  "nevada.notice.again": ["bigsis", "Sector 44. Sector 1250. Years. I am almost certain. 'Almost' is the part I don't like."],

  "nevada.coin.read.1": ["bigsis", "Mother. This is a Roman denarius. And that is Julius Caesar."],
  "nevada.coin.read.2": ["bigsis", "Fun fact: he was the first living Roman to put his own face on Rome's coins. He started in 44 B.C."],
  "nevada.coin.read.3": ["bigsis", "And it isn't two thousand years old. Look at the edges. It is NEW. It has hardly been in a pocket."],
  "nevada.coin.read.4": ["mom", "A new coin, from 44 B.C., that fell out of the sky. In Nevada."],
  "nevada.coin.lilsis": ["lilsis", "A money! With a grumpy man on it. Can I buy a lemonade with it?"],
  "nevada.coin.mom": ["mom", "Thank you, darling. I will keep it in my handbag, with everything else that matters."],
  "nevada.connect": ["bigsis", "Sector 44. A new coin from 44 B.C. It is the same forty-four. The holes don't go to places. They go to YEARS."],

  "nevada.tracks.look.mom": ["mom", "Tire tracks. They come in from the road and they simply... stop. At a patch of sand that has turned to glass."],
  "nevada.tracks.look.bigsis": ["bigsis", "It takes a furnace to turn sand into glass. Something here was very hot, very briefly."],
  "nevada.tracks.look.lilsis": ["lilsis", "The ground is SHINY. And the air's all wobbly, like over the toaster."],
  "nevada.tracks.early.mom": ["mom", "Not yet, darlings. I would like to understand it before any of us stands on it."],
  "nevada.tracks.early.bigsis": ["bigsis", "I have a theory. A theory is not a fact until I can footnote it."],
  "nevada.tracks.early.lilsis": ["lilsis", "Can I jump on it? ...Mommy's doing the eyebrow. That's a no."],
  "nevada.gate.1": ["bigsis", "The tracks don't turn. They don't skid. They just stop."],
  "nevada.gate.2": ["bigsis", "Sector 44: forty-four B.C., the year Julius Caesar was killed, on the Ides of March. Sector 1250: twelve-fifty B.C., with Ramesses the Great on the throne of Egypt."],
  "nevada.gate.3": ["bigsis", "They didn't crash, Mother. They didn't go anywhere. They went some WHEN."],
  "nevada.gate.4": ["lilsis", "I TOLD you! Daddy's not lost! Daddy's EARLY!"],
  "nevada.gate.5": ["bigsis", "...More than three thousand years early. She was right. I need to sit down."],
  "nevada.gate.6": ["mom", "Then we know where they are. Now we only have to find out how one gets there."],
  "nevada.gate.7": ["mom", "Girls. We are going to go and bring them home."],

  "nevada.car.look.mom": ["mom", "My car. It has never once taken a shortcut. It is the only vehicle in this family still in this century."],
  "nevada.car.look.bigsis": ["bigsis", "Mom's car. She parked it parallel to nothing. Perfectly."],
  "nevada.car.look.lilsis": ["lilsis", "I get the front seat on the way home. I called it. I called it in the DRIVEWAY."],
  "nevada.shack.mom": ["mom", "'Last Stop.' I do hope that is geography and not a prediction."],
  "nevada.shack.bigsis": ["bigsis", "A building held together by paint and optimism. Mostly optimism."],
  "nevada.shack.lilsis": ["lilsis", "They sell ROCKS. You can just FIND rocks. This is the best shop ever."],
  "nevada.pump.mom": ["mom", "A gas pump with no gas in it. There is a great deal of that about."],
  "nevada.pump.bigsis": ["bigsis", "'The pump,' she noted, 'had not served a customer in her lifetime. Or, by the look of it, in her mother's.'"],
  "nevada.pump.lilsis": ["lilsis", "It has a ball on its head. Like a lollipop for cars."],
  "nevada.stand.mom": ["mom", "'Lemonade, one dollar. Rocks, two dollars. Stories extra.' An honest price list."],
  "nevada.stand.bigsis": ["bigsis", "Quartz, sandstone, and one that is just a rock. I respect the honesty."],
  "nevada.stand.lilsis": ["lilsis", "Lemonade! Mommy! LEMONADE! ...Please."],
  "nevada.fence.mom": ["mom", "A fence, put up in a hurry by people who were not expecting visitors."],
  "nevada.fence.bigsis": ["bigsis", "The posts are new, and the concrete around them is still dark. This fence went up yesterday."],
  "nevada.fence.lilsis": ["lilsis", "I could fit under that. ...I'm just SAYING."],

  "nevada.talk.mom.bigsis.1a": ["mom", "What do you make of it, darling?"],
  "nevada.talk.mom.bigsis.1b": ["bigsis", "It is too tidy. Real accidents are messy. This one has a fence and a sign."],
  "nevada.talk.mom.bigsis.2a": ["mom", "You have not opened your book once since we left the house."],
  "nevada.talk.mom.bigsis.2b": ["bigsis", "This is better than the book. Do not tell the book."],
  "nevada.talk.mom.bigsis.2c": ["mom", "Your secret is safe, darling."],
  "nevada.talk.mom.bigsis.coin.a": ["mom", "The gentleman gave me a coin. I would like your opinion of it."],
  "nevada.talk.mom.bigsis.coin.b": ["bigsis", "Then hand it over, Mother. I can't footnote what I can't hold."],
  "nevada.talk.mom.lilsis.1a": ["mom", "Drink your lemonade slowly, sweetheart."],
  "nevada.talk.mom.lilsis.1b": ["lilsis", "I AM drinking it slowly. I'm drinking it slowly really FAST."],
  "nevada.talk.mom.lilsis.2a": ["lilsis", "Mommy, is Daddy in trouble?"],
  "nevada.talk.mom.lilsis.2b": ["mom", "A little, sweetheart. But only with me, and only once he is home."],
  "nevada.talk.mom.lilsis.gray.a": ["mom", "That gentleman in gray will not move for me."],
  "nevada.talk.mom.lilsis.gray.b": ["lilsis", "Did you ask him enough times? You have to ask a LOT of times."],
  "nevada.talk.bigsis.mom.1a": ["bigsis", "For the record: I am not frightened. I am gathering data."],
  "nevada.talk.bigsis.mom.1b": ["mom", "Gather it close to me, please."],
  "nevada.talk.bigsis.mom.2a": ["bigsis", "Mom. If I turn out to be right about this, may I say so?"],
  "nevada.talk.bigsis.mom.2b": ["mom", "Once, darling. Graciously."],
  "nevada.talk.bigsis.mom.2c": ["bigsis", "...I'll practice."],
  "nevada.talk.bigsis.lilsis.2a": ["bigsis", "Stay where I can see you."],
  "nevada.talk.bigsis.lilsis.2b": ["lilsis", "You stay where I can see YOU. I'm the one with the boots."],
  "nevada.talk.bigsis.lilsis.gray.a": ["bigsis", "I need that man to look somewhere else for sixty seconds."],
  "nevada.talk.bigsis.lilsis.gray.b": ["lilsis", "I can do sixty HOURS."],
  "nevada.talk.bigsis.lilsis.1a": ["lilsis", "What's radiator levels?"],
  "nevada.talk.bigsis.lilsis.1b": ["bigsis", "Radiation. It's a kind of energy you can't see."],
  "nevada.talk.bigsis.lilsis.1c": ["lilsis", "Like me when I hide?"],
  "nevada.talk.bigsis.lilsis.1d": ["bigsis", "No. You are extremely visible. And audible."],
  "nevada.talk.lilsis.mom.1a": ["lilsis", "Mommy, the old man has a beard like Santa. Is he Santa on vacation?"],
  "nevada.talk.lilsis.mom.1b": ["mom", "If he is, darling, we have been very good this year."],
  "nevada.talk.lilsis.mom.2a": ["lilsis", "Mommy, when we find Daddy, can I tell him I fixed the internet?"],
  "nevada.talk.lilsis.mom.2b": ["mom", "You may tell him first, before anybody says anything else at all."],
  "nevada.talk.lilsis.mom.2c": ["lilsis", "Even before 'hi'?"],
  "nevada.talk.lilsis.bigsis.2a": ["lilsis", "Are you scared?"],
  "nevada.talk.lilsis.bigsis.2b": ["bigsis", "No. ...A little. Hold my book."],
  "nevada.talk.lilsis.bigsis.2c": ["lilsis", "I'm holding it MIGHTILY."],
  "nevada.talk.lilsis.bigsis.1a": ["lilsis", "I'm small but I'm mighty."],
  "nevada.talk.lilsis.bigsis.1b": ["bigsis", "You are small but you are LOUD. It is a different thing."],
  "nevada.talk.lilsis.bigsis.1c": ["lilsis", "It's the SAME thing."],

  // ---------- the sketch example scene ----------
  "sketch.stall": ["son", "Placeholder fruit. It tastes like a to-do list."],
  "sketch.gate": ["son", "This gate isn't drawn yet. It's still very impressive. Nine out of ten, for a rectangle."],
  "sketch.cart": ["son", "A cart, according to the label."],
  "sketch.cart.use": ["son", "I'd push it, but it's mostly a rectangle."],

  // ---------- carried things ----------
  "item.map.look": ["dad", "A road map. It folds eleven ways and none of them is the way it came."],
  "item.reed.look": ["dad", "A reed. The pen of the future, about three thousand years ago."],
  "item.coin.look": ["son", "A coin with a serious man on it. He looks like he has never had a snack in his life."],
  "item.coin.mom": ["mom", "A silver coin with a stern gentleman on it. It looks old and it looks new. Your sister will know which."],
  "item.coin.bigsis": ["bigsis", "A denarius of Julius Caesar, struck in 44 B.C. and not a day older. I am not letting go of it."],
  "item.coin.lilsis": ["lilsis", "A money, with a grumpy man on it. He needs a snack."],
  "item.note.mom": ["mom", "'The year of the best thing since.' Your sister will know. She knows the year of everything."],
  "item.note.bigsis": ["bigsis", "Sliced bread, 1928. I am keeping this. It is a primary source."],
  "item.note.lilsis": ["lilsis", "Words. I'll give it to somebody with glasses."],

  // ---------- looking at each other ----------
  "see.mom.bigsis": ["mom", "My eldest. Thirteen, and she can read anything in the world except a room."],
  "see.mom.lilsis": ["mom", "My youngest. Seven years old, and entirely without brakes."],
  "see.bigsis.mom": ["bigsis", "Mom. She has not raised her voice once tonight. That is how I know it is serious."],
  "see.bigsis.lilsis": ["bigsis", "My sister. Small, loud, and occasionally useful. Do not tell her I said useful."],
  "see.lilsis.mom": ["lilsis", "Mommy. She smells like the good soap."],
  "see.lilsis.bigsis": ["lilsis", "My sister. She knows EVERYTHING. It's so annoying."],

  // ---------- handing something over ----------
  "give.dad.1": ["dad", "Here, buddy. Don't say I never gave you anything."],
  "give.son.1": ["son", "Here! Hot potato! It's not a potato."],
  "give.mom.1": ["mom", "Would you take this for me, darling?"],
  "give.bigsis.1": ["bigsis", "Here. Do not lose it. I have cataloged it."],
  "give.lilsis.1": ["lilsis", "Here! Hold this! It's IMPORTANT!"],

  // ---------- hints. One per puzzle for the lead who does it; in a team, one from each of the others to say whose job it is. ----------
  "hint.egypt.reed": ["dad", "The scribe lost his pen. Something by the river might do for a new one."],
  "hint.egypt.map": ["dad", "I should check what's still in the wagon."],
  "hint.egypt.pen": ["dad", "I have a reed, and I know a man who needs a pen."],
  "hint.egypt.mark": ["dad", "The scribe wants something to draw on. A map is mostly drawing."],
  "hint.egypt.leave": ["dad", "The door is holding still now. Time to go through it."],
  "hint.rome.coin": ["son", "That fountain is full of other people's wishes. I only need to borrow one."],
  "hint.rome.toss": ["son", "The humming door ate me. Maybe it eats money too. For science."],

  "hint.home.router.lilsis": ["lilsis", "The computer says NO internet. The internet lives in the closet under the stairs. I bet I fit."],
  "hint.home.router.mom": ["mom", "The router is in the closet under the stairs, and that door barely opens. It is a job for someone small."],
  "hint.home.router.bigsis": ["bigsis", "No connection. The router is in the closet, behind a door only my sister fits through. I will let her have this one."],
  "hint.home.note.bigsis": ["bigsis", "Dad always writes his passwords down. There is a yellow note on the monitor. I should read it."],
  "hint.home.note.mom": ["mom", "Your father left a note on the monitor. It is a riddle about a year, and your sister is the one for years."],
  "hint.home.note.lilsis": ["lilsis", "There's a yellow sticky on the computer with words on it. Words are for my sister."],
  "hint.home.login.mom": ["mom", "We have the internet and we have the password. I will sit down at that computer myself."],
  "hint.home.login.bigsis": ["bigsis", "The router is on and the password is 1928. After that it asks about the wedding. That is Mom's department."],
  "hint.home.login.lilsis": ["lilsis", "I fixed the internet and my sister did the number. Now Mommy has to do the typing."],
  "hint.home.leave.mom": ["mom", "We know where that phone was last seen. The front door, girls."],
  "hint.home.leave.bigsis": ["bigsis", "We have a location. The logical next step is the front door."],
  "hint.home.leave.lilsis": ["lilsis", "We found the dot! Let's GO! The door is right THERE!"],

  "hint.nevada.witness.mom": ["mom", "The gentleman in the lawn chair has watched this road for forty years. Nobody has asked him nicely."],
  "hint.nevada.witness.bigsis": ["bigsis", "The old man is a witness, and he doesn't care for my questions. Mom could get a statue to talk."],
  "hint.nevada.witness.lilsis": ["lilsis", "The wizard man won't tell ME. He wants a dollar. Mommy has dollars AND manners."],
  "hint.nevada.coin.mom": ["mom", "I have a silver coin I cannot read. I should hand it to the one of us who can."],
  "hint.nevada.coin.bigsis": ["bigsis", "Mom is carrying a coin that fell out of the sky. I need to see it. In my own hands."],
  "hint.nevada.coin.lilsis": ["lilsis", "Mommy got a shiny money from the wizard. My sister knows about olden-days stuff."],
  "hint.nevada.distract.lilsis": ["lilsis", "The gray man is standing in front of the sign. I have SO many questions for him."],
  "hint.nevada.distract.mom": ["mom", "That man will not move for courtesy. He has not yet met your little sister."],
  "hint.nevada.distract.bigsis": ["bigsis", "He can deflect one question. Can he deflect two hundred? I know someone who has two hundred."],
  "hint.nevada.notice.bigsis": ["bigsis", "The man in gray has his hands full. Now I can read that notice properly."],
  "hint.nevada.notice.mom": ["mom", "The notice is free at last. Your sister should be the one to read it. She reads between the lines."],
  "hint.nevada.notice.lilsis": ["lilsis", "I got the gray man out of the way! Somebody who can read fast should go and read!"],
  "hint.nevada.tracks.mom": ["mom", "A coin from one year, and a notice with two. It all leads to where those tracks stop."],
  "hint.nevada.tracks.bigsis": ["bigsis", "I have the coin and I have the sectors. The proof is where the tire tracks end."],
  "hint.nevada.tracks.lilsis": ["lilsis", "The shiny ground! Where the car tracks stop! Let's all go and look!"],

  // ---------- stock replies ----------
  "nope.dad.1": ["dad", "That's not how I'd do it. And I'd do almost anything."],
  "nope.dad.2": ["dad", "No. But I respect the idea."],
  "nope.dad.3": ["dad", "That won't work. Trust me, I've read half a manual."],
  "nope.son.1": ["son", "That doesn't work. I checked. In my head. Twice."],
  "nope.son.2": ["son", "Nope. Nopity nope. Zero out of ten."],
  "nope.son.3": ["son", "Bad plan. I only do GOOD bad plans."],
  "nope.mom.1": ["mom", "No, darling. That would not do at all."],
  "nope.mom.2": ["mom", "I think not. Let us try something more sensible."],
  "nope.mom.3": ["mom", "A creative idea. We will not be using it."],
  "nope.bigsis.1": ["bigsis", "That will not work. I can give you three reasons, in order."],
  "nope.bigsis.2": ["bigsis", "No. Historically, that has never once worked."],
  "nope.bigsis.3": ["bigsis", "'It was,' she noted, 'a terrible idea.'"],
  "nope.lilsis.1": ["lilsis", "NO. It doesn't go."],
  "nope.lilsis.2": ["lilsis", "That's silly. And I KNOW silly."],
  "nope.lilsis.3": ["lilsis", "Nope! Do I get a snack for trying?"],
  "look.dad.1": ["dad", "Nothing to write home about. Not that the mail goes there yet."],
  "look.son.1": ["son", "It's a thing. I'm looking at it. It's looking back. I win."],
  "look.mom.1": ["mom", "Nothing that needs me. How restful."],
  "look.bigsis.1": ["bigsis", "Unremarkable. I have remarked on it anyway."],
  "look.lilsis.1": ["lilsis", "It's just a thing. BORING. Next!"],
  "hint.dad.none": ["dad", "I've got nothing. Let's look around."],
  "hint.son.none": ["son", "No idea. I'll poke things until something happens. That's called science."],
  "hint.mom.none": ["mom", "I have no idea, my love. Let us look around properly."],
  "hint.bigsis.none": ["bigsis", "I don't know. ...I am writing that down. It doesn't happen often."],
  "hint.lilsis.none": ["lilsis", "I dunno. Let's ask somebody tall."],
};
