// Act Three: home, that evening. Mom, Big Sister and Little Sister.
//   "line.id": ["who", "What they say."]
// docs/CHARACTERS.md says how each of them talks. Every fact Big Sister states is true (the table is in that file).

export const lines = {
  // ---------- home, that evening: Mom, Big Sister, Little Sister ----------
  "home.arrive.vm1": ["dad", "'You've reached Dad. I can't pick up right now. I'm either driving or lost.'"],
  "home.arrive.vm2": ["dad", "'And I am never lost. So: driving. Leave a message.'"],
  "home.arrive.1": ["mom", "Voicemail. That is the ninth time. I had decided to stop worrying at eight."],
  "home.arrive.2": ["lilsis", "Daddy's not lost. Daddy's EARLY."],
  "home.arrive.2b": ["bigsis", "That is not what early means."],
  "home.arrive.3": ["bigsis", "They left at noon. It is a four-hour drive. It is now nine forty. For the record, that is not a shortcut."],
  "home.arrive.4": ["mom", "Dinner was at six. I set five places, and I am not clearing two of them away."],
  "home.arrive.5": ["bigsis", "His phone still tells the family computer where it is. Dad set that up himself. He called it 'the mainframe'."],
  "home.arrive.6": ["lilsis", "Then the computer KNOWS! Ask the computer!"],
  "home.arrive.7": ["mom", "Then that is where we begin, girls. We are going to find out where that phone was last seen."],

  "home.pc.look.mom": ["mom", "The family computer. Your father calls it 'the mainframe'. It is nine years old and it sighs when you switch it on."],
  "home.pc.look.bigsis": ["bigsis", "Our computer. It runs the family map. It also runs. Technically."],
  "home.pc.look.lilsis": ["lilsis", "The computer! It has a game where a cat eats numbers."],
  "home.pc.offline.mom": ["mom", "'No internet.' I see. It was working perfectly well until your father improved it."],
  "home.pc.offline.bigsis": ["bigsis", "No connection. Fun fact: the first message ever sent on the network that became the internet was 'LO'. They were typing LOGIN, and it crashed. October 1969."],
  "home.pc.offline.bigsis2": ["bigsis", "So this is traditional."],
  "home.pc.offline.lilsis": ["lilsis", "It says NO. Computers aren't allowed to say no. I'm telling Mommy."],
  "home.pc.router": ["mom", "The router lives in the closet under the stairs. Your father keeps the internet next to the vacuum cleaner."],
  "home.pc.login.mom": ["mom", "It wants a password. Four numbers. 'Forgot it? Ask Dad.' I would dearly love to."],
  "home.pc.login.bigsis": ["bigsis", "Four digits. Ten thousand possibilities. Dad will have written it down somewhere. He always does."],
  "home.pc.login.lilsis": ["lilsis", "One, two, three, four! ... It said no AGAIN."],
  "home.pc.type.mom": ["mom", "One. Nine. Two. Eight."],
  "home.pc.type.bigsis": ["bigsis", "One, nine, two, eight. I type with all ten fingers. It is not difficult."],
  "home.pc.type.lilsis": ["lilsis", "One! Nine! Two! Eight! I typed it with ONE finger."],
  "home.pc.question.mom": ["mom", "'What did you promise on your wedding day?' Oh, my love. You would."],
  "home.pc.question.bigsis": ["bigsis", "'What did you promise on your wedding day?' I was not invited to the wedding. Mother?"],
  "home.pc.question.lilsis": ["lilsis", "It's asking about a wedding. I wasn't BORN. Mommy!"],
  "home.pc.pick.love": ["mom", "To love, honor and cherish."],
  "home.pc.pick.scenic": ["mom", "To always take the scenic route."],
  "home.pc.pick.directions": ["mom", "To never ask for directions."],
  "home.pc.wrong.love": ["mom", "No? I did say that. I had hoped he was listening."],
  "home.pc.wrong.scenic": ["mom", "No. That was not a promise. That was a warning."],
  "home.pc.right": ["mom", "He promised me he would never ask for directions. It is the one promise he has always kept."],
  "home.pc.map.1": ["mom", "There. 'Dad's phone. Last seen 5:47 p.m. Thirty-seven miles past Last Gas.' In the middle of Nevada."],
  "home.pc.map.2": ["bigsis", "That is not on the way home. That is not on the way to anywhere."],
  "home.pc.map.3": ["lilsis", "Is Nevada past the mailbox?"],
  "home.pc.map.4": ["mom", "A little past the mailbox, darling. Shoes on, both of you. We leave tonight."],
  "home.pc.done.mom": ["mom", "One dot, in the middle of nothing. I have looked at it quite long enough."],
  "home.pc.done.bigsis": ["bigsis", "Thirty-seven miles past Last Gas. I have memorized it. I memorize everything."],
  "home.pc.done.lilsis": ["lilsis", "The dot is Daddy. Hi, dot."],

  "home.note.look.mom": ["mom", "Your father's handwriting. 'Password: the year of the best thing since.' Since WHAT, my love? He has left off the end."],
  "home.note.look.lilsis": ["lilsis", "It says 'PASS WORD'. And then more words. Daddy does the loopy Ys."],
  "home.note.take.mom": ["mom", "I will hold on to this. It is the nearest thing to your father in the house."],
  "home.note.take.lilsis": ["lilsis", "MINE. I mean: evidence."],
  "home.note.solve.1": ["bigsis", "'Password: the year of the best thing since.' ...Since sliced bread. With Dad, everything is the best thing since sliced bread."],
  "home.note.solve.2": ["bigsis", "Fun fact: sliced bread was first sold on the seventh of July, 1928, in Chillicothe, Missouri."],
  "home.note.solve.3": ["bigsis", "The password is 1928. Dad, that is so... actually, that is quite good."],

  "home.closet.look.mom": ["mom", "The closet under the stairs. Something has fallen against the door from inside. It opens exactly this far."],
  "home.closet.look.bigsis": ["bigsis", "The door opens four inches. I am wider than four inches. I have shoulders."],
  "home.closet.look.lilsis": ["lilsis", "It's dark in there. And there's a tiny light! That's the internet. The internet is TINY."],
  "home.closet.use.mom": ["mom", "A lady does not squeeze into closets, darling. A lady has a seven-year-old."],
  "home.closet.use.bigsis": ["bigsis", "I refuse. There are spiders in there, and I am thirteen. Both of those are final."],
  "home.closet.go.1": ["lilsis", "I FIT!"],
  "home.closet.go.2": ["lilsis", "It's SO dark. There's the vacuum. And Daddy's golf sticks. And a plug that isn't plugged into anything!"],
  "home.closet.go.3": ["mom", "Into the wall, sweetheart. The socket with two little eyes and a surprised mouth."],
  "home.closet.go.4": ["lilsis", "The red light went GREEN! I fixed the internet! I'm a ENGINEER!"],
  "home.closet.go.5": ["bigsis", "AN engineer."],
  "home.closet.go.6": ["lilsis", "That's what I SAID."],
  "home.closet.again": ["lilsis", "I already fixed it. It's green. Green means I'm good at it."],
  "home.closet.done.mom": ["mom", "A small green light. Clever girl."],
  "home.closet.done.bigsis": ["bigsis", "The light is green. She will be insufferable for a week."],

  "home.piano.look.mom": ["mom", "Your sister's piano. The one thing in this house that is always in tune."],
  "home.piano.look.bigsis": ["bigsis", "My piano. Fun fact: Bartolomeo Cristofori built the first one, in Florence, around the year 1700."],
  "home.piano.look.bigsis2": ["bigsis", "They called it a harpsichord with soft and loud. I would have called it a miracle."],
  "home.piano.look.lilsis": ["lilsis", "The piano. I know one song. It's the one with two fingers."],
  "home.piano.use.mom": ["mom", "Not tonight. Tonight I would only play something sad, and play it badly."],
  "home.piano.use.bigsis": ["bigsis", "Something in a minor key. It felt appropriate."],
  "home.piano.use.bigsis2": ["bigsis", "When Dad is home I will play the loud one he likes. Twice."],
  "home.piano.use.lilsis": ["lilsis", "PLONK. That was my song. It's called 'Plonk'."],

  "home.books.mom": ["mom", "Your sister's novels and your father's manuals. The novels have been finished."],
  "home.books.bigsis": ["bigsis", "My books. Alphabetical by author, and then by how much I cried."],
  "home.books.lilsis": ["lilsis", "Too many words. I like the one about the duck. The duck has NO words."],
  "home.photo.mom": ["mom", "The five of us at the lake. Your father took a shortcut that day, too. We saw a great deal of the lake."],
  "home.photo.bigsis": ["bigsis", "Five people, one tripod. Dad set the timer and ran. He is the blur."],
  "home.photo.lilsis": ["lilsis", "That's me! I was SIX. I'm way bigger now. Almost."],
  "home.table.mom": ["mom", "Roast chicken at six o'clock sharp. It is no longer sharp."],
  "home.table.bigsis": ["bigsis", "'The table,' she observed, 'was set for five. The house was not.'"],
  "home.table.lilsis": ["lilsis", "Can I have Daddy's potatoes? He's not using them."],
  "home.chair.mom": ["mom", "Your father's chair. It has kept his shape. I find I rather like that tonight."],
  "home.chair.bigsis": ["bigsis", "Dad's chair. His crossword is on the arm. Seven across is wrong. I haven't told him."],
  "home.chair.lilsis": ["lilsis", "Daddy's chair. If you sit in it you have to say 'well, well, well'."],
  "home.window.mom": ["mom", "No headlights. I have looked eleven times. Twelve."],
  "home.window.bigsis": ["bigsis", "'The street,' she wrote, 'was the wrong kind of quiet.' ...That's good. I'm keeping that."],
  "home.window.lilsis": ["lilsis", "I'm watching for the car. I'm the best at watching. I haven't blinked since dinner."],
  "home.stairs.mom": ["mom", "Nobody is going up to bed tonight. Least of all me."],
  "home.stairs.bigsis": ["bigsis", "Thirteen steps. Yes, I counted. I count in fours when I'm nervous, and thirteen doesn't divide."],
  "home.stairs.lilsis": ["lilsis", "I'm not tired. I'm NEVER tired. ...What time is it?"],
  "home.door.early.mom": ["mom", "Not until we know where we are going. One of us in this family must."],
  "home.door.early.bigsis": ["bigsis", "We don't have a destination. A journey without a destination is just Dad."],
  "home.door.early.lilsis": ["lilsis", "I'm not allowed out after dark. Unless it's a 'mergency. Is it a 'mergency?"],
  "home.leave.1": ["mom", "Coats, girls. We are going to Nevada."],
  "home.leave.2": ["bigsis", "I'll bring the atlas. And a book. And a second book, in case the first one ends."],
  "home.leave.3": ["lilsis", "I'll bring my boots! I'm already WEARING my boots!"],
  "home.leave.4": ["mom", "We are going to be perfectly polite, and completely impossible to get rid of."],

  "home.talk.mom.bigsis.1a": ["mom", "You are very quiet, darling."],
  "home.talk.mom.bigsis.1b": ["bigsis", "I am thinking. It only looks like quiet from the outside."],
  "home.talk.mom.bigsis.2a": ["mom", "Whatever has happened, we will deal with it the way we deal with everything."],
  "home.talk.mom.bigsis.2b": ["bigsis", "With a list?"],
  "home.talk.mom.bigsis.2c": ["mom", "With a list."],
  "home.talk.mom.lilsis.1a": ["mom", "Are you frightened, sweetheart?"],
  "home.talk.mom.lilsis.1b": ["lilsis", "No! ...Are YOU?"],
  "home.talk.mom.lilsis.1c": ["mom", "Not while I have you to look after me."],
  "home.talk.mom.lilsis.2a": ["lilsis", "Mommy, why did Daddy take a shortcut?"],
  "home.talk.mom.lilsis.2b": ["mom", "Because the long way around has never once been his idea."],
  "home.talk.bigsis.mom.1a": ["bigsis", "Mom. Statistically, they are fine."],
  "home.talk.bigsis.mom.1b": ["mom", "Thank you, darling. And unstatistically?"],
  "home.talk.bigsis.mom.1c": ["bigsis", "...Also fine. Probably."],
  "home.talk.bigsis.mom.2a": ["bigsis", "I've started a new chapter. It is called 'The Night They Didn't Come Home'."],
  "home.talk.bigsis.mom.2b": ["mom", "Do give it a happy ending."],
  "home.talk.bigsis.lilsis.1a": ["bigsis", "Don't touch anything while I'm thinking."],
  "home.talk.bigsis.lilsis.1b": ["lilsis", "I'm not touching. I'm HOLDING."],
  "home.talk.bigsis.lilsis.2a": ["lilsis", "Why do you know so many years?"],
  "home.talk.bigsis.lilsis.2b": ["bigsis", "Because somebody has to. Years don't remember themselves."],
  "home.talk.lilsis.mom.1a": ["lilsis", "Mommy, I can help. I'm small but I'm MIGHTY."],
  "home.talk.lilsis.mom.1b": ["mom", "You are the mightiest person I know, my love. Do aim it carefully."],
  "home.talk.lilsis.mom.2a": ["lilsis", "Can I stay up?"],
  "home.talk.lilsis.mom.2b": ["mom", "Tonight, yes."],
  "home.talk.lilsis.mom.2c": ["lilsis", "...Now I'm worried."],
  "home.talk.lilsis.bigsis.1a": ["lilsis", "Read me a fact."],
  "home.talk.lilsis.bigsis.1b": ["bigsis", "It's 'tell me a fact'."],
  "home.talk.lilsis.bigsis.1c": ["lilsis", "Tell me a READ."],
  "home.talk.lilsis.bigsis.2a": ["lilsis", "My tooth is loose. Look. LOOK."],
  "home.talk.lilsis.bigsis.2b": ["bigsis", "I have seen the tooth. Everyone on this street has seen the tooth."],


  // ---------- carried things ----------
  "item.note.mom": ["mom", "'The year of the best thing since.' Your sister will know. She knows the year of everything."],
  "item.note.bigsis": ["bigsis", "Sliced bread, 1928. I am keeping this. It is a primary source."],
  "item.note.lilsis": ["lilsis", "Words. I'll give it to somebody who reads books with NO pictures."],

  // ---------- hints: one from each of them for every puzzle ----------
  "hint.home.router.lilsis": ["lilsis", "The computer says NO internet. The internet lives in the closet under the stairs. I bet I fit."],
  "hint.home.router.mom": ["mom", "The router is in the closet under the stairs, and that door barely opens. It is a job for someone small."],
  "hint.home.router.bigsis": ["bigsis", "No connection. The router is in the closet, behind a door only my sister fits through. I will let her have this one."],
  "hint.home.note.bigsis": ["bigsis", "Dad always writes his passwords down. There is a yellow note on the monitor. I should read it."],
  "hint.home.note.mom": ["mom", "Your father left a note on the monitor. It is a riddle about a year, and your sister is the one for years."],
  "hint.home.note.lilsis": ["lilsis", "There's a yellow sticky on the computer with words on it. Words are for my sister."],
  "hint.home.login.mom": ["mom", "We have the internet and we have the password. I will sit down at that computer myself."],
  "hint.home.login.bigsis": ["bigsis", "The router is on and the password is 1928. After that it asks about the wedding. That is Mom's department."],
  "hint.home.login.lilsis": ["lilsis", "I fixed the internet and my sister did the number. Now Mommy has to do the typing."],
  "hint.home.leave.mom": ["mom", "We know where that phone was last seen. The front door, girls."],
  "hint.home.leave.bigsis": ["bigsis", "We have a location. The logical next step is the front door."],
  "hint.home.leave.lilsis": ["lilsis", "We found the dot! Let's GO! The door is right THERE!"],
};
