// Act Four: the middle of Nevada, the next morning.
//   "line.id": ["who", "What they say."]
// docs/CHARACTERS.md says how each of them talks. Every fact Big Sister states is true (the table is in that file).
//
// The door in time where the tracks stop is shut and cannot be seen until the last beat: nobody says the air
// wobbles or shimmers. It hums. What opens it is light, and the only one who has seen that happen is the
// old-timer, who tells it without knowing which part of his story matters (nevada.old.saw.1b and nevada.old.saw.2).

export const lines = {
  // ---------- the middle of Nevada, the next morning ----------
  "nevada.arrive.1": ["mom", "Thirty-seven miles past Last Gas. This is where the map stops."],
  "nevada.arrive.2": ["bigsis", "Fun fact: Nevada became a state on the thirty-first of October, 1864. Halloween."],
  "nevada.arrive.3": ["lilsis", "It's all DIRT. Who ordered this much dirt?"],
  "nevada.arrive.4": ["mom", "Somebody here saw something. We will ask nicely. Stay where I can see you, girls."],

  // ---------- chain A: the old-timer ----------
  "nevada.old.look.mom": ["mom", "A gentleman in a lawn chair, selling rocks and lemonade to a road with no cars on it. He will have seen whatever passed."],
  "nevada.old.look.bigsis": ["bigsis", "One witness. Elderly, seated, hat. He is pretending not to watch us. Badly."],
  "nevada.old.look.lilsis": ["lilsis", "He's got a white beard like a wizard. A wizard who sells ROCKS."],
  "nevada.old.lilsis.1": ["lilsis", "Mister, did you see my daddy? He's tall and he has a moustache and he's EARLY."],
  "nevada.old.lilsis.2": ["oldtimer", "Lemonade's a dollar, little miss. Stories are extra."],
  "nevada.old.lilsis.3": ["lilsis", "I don't HAVE a dollar. I have a tooth."],
  "nevada.old.bigsis.1": ["bigsis", "Sir. Did you observe a red station wagon yesterday at approximately 5:47 p.m.?"],
  "nevada.old.bigsis.2": ["oldtimer", "Didn't see nothing. Been not seeing nothing out here for forty years."],
  "nevada.old.bigsis.3": ["bigsis", "That is a double negative. Technically, you saw something."],
  "nevada.old.bigsis.4": ["oldtimer", "Technically, I'm closed."],
  "nevada.old.mom.1": ["mom", "Good morning. Forgive us for troubling you. May I buy three lemonades, and a few minutes of your time?"],
  "nevada.old.mom.2": ["oldtimer", "Well, now. Forty years out here, and you're the first one to say good morning."],
  "nevada.old.mom.3": ["oldtimer", "Folks come asking about yesterday. Men in gray suits, mostly. I tell 'em I didn't see nothing."],
  "nevada.old.mom.4": ["mom", "And did you see nothing?"],
  "nevada.old.mom.5": ["oldtimer", "Depends who's asking. You kin to whoever was in that car?"],
  "nevada.old.mom.6": ["mom", "My husband and my son."],
  "nevada.old.mom.7": ["oldtimer", "Then tell me what they were driving. The gray suits couldn't."],
  "nevada.car.wagon": ["mom", "A red station wagon with wood on the sides and far too much luggage on the roof."],
  "nevada.car.sedan": ["mom", "A sensible silver sedan."],
  "nevada.car.black": ["mom", "A black car with dark windows."],
  "nevada.car.no.sedan": ["oldtimer", "No, ma'am. Nothing sensible came down this road yesterday."],
  "nevada.car.no.black": ["oldtimer", "That's what the gray suits drive. Try again."],
  // What he saw. The flash of low sun is the part that matters, and he does not know it.
  "nevada.old.saw.1": ["oldtimer", "That's the one. Red wagon, wood trim, cooler on the roof. Driver waved at me. Nobody waves anymore."],
  "nevada.old.saw.1b": ["oldtimer", "Sun was low. Hit the chrome on that wagon and threw a flash up ahead, like a signal mirror."],
  "nevada.old.saw.2": ["oldtimer", "Right where it landed, the sky opened up like a tin can. The road sign changed its mind. And that wagon drove straight in."],
  "nevada.old.saw.3": ["oldtimer", "Hour later the gray suits came and put up a fence. 'Radiation,' they say. Third piece of desert they've shut this year."],
  "nevada.old.saw.4": ["mom", "Thank you. You have been kinder than you needed to be."],
  "nevada.old.saw.5": ["oldtimer", "One more thing. This fell out of the sky this morning. Hit my hat. Seems like it's yours more than mine."],
  "nevada.old.saw.6": ["mom", "A silver coin. With a very serious gentleman on it."],
  "nevada.ask.flash": ["mom", "Tell me again about the flash of light."],
  "nevada.ans.flash": ["oldtimer", "Low sun on bright chrome, ma'am. One flash, up ahead. And where it fell, the sky came open. Never seen the like."],
  "nevada.ask.fence": ["mom", "What is behind the fence?"],
  "nevada.ans.fence": ["oldtimer", "Used to be nothing. Now it's nothing with a fence around it."],
  "nevada.ask.areas": ["mom", "You said they have closed other places."],
  "nevada.ans.areas": ["oldtimer", "Three this year. Always the same sign. 'Elevated radiation.' Funny thing is, my old Geiger counter never clicks once."],
  "nevada.ask.bye": ["mom", "We must not keep you."],
  "nevada.ans.bye": ["oldtimer", "You ain't. I got all day. I got all decade."],
  "nevada.old.after.lilsis.1": ["oldtimer", "Your ma's good people. Lemonade's on the house, little miss."],
  "nevada.old.after.lilsis.2": ["lilsis", "On the house? WHERE'S the house?"],
  "nevada.old.after.bigsis.1": ["bigsis", "Sir. They say radiation. Do you own anything that measures it?"],
  "nevada.old.after.bigsis.2": ["oldtimer", "My daddy's Geiger counter. Clicked fine for him in fifty-seven. Hasn't clicked once this year."],
  "nevada.old.after.bigsis.3": ["bigsis", "Then somebody is lying, and it isn't the Geiger counter. Interesting."],
  "nevada.old.coin": ["mom", "He gave it to us, darling. It would be rude to give it back."],

  // ---------- chain B: the man in gray, and the notice ----------
  "nevada.agent.look.mom": ["mom", "A man in a gray suit, standing precisely in front of the one thing worth reading."],
  "nevada.agent.look.bigsis": ["bigsis", "Gray suit, gray tie, dark glasses. He is standing in front of that notice on purpose. That is called obstruction."],
  "nevada.agent.look.lilsis": ["lilsis", "He's ALL gray. Is his dog gray?"],
  "nevada.agent.mom.1": ["mom", "Good morning. May we read the notice behind you?"],
  "nevada.agent.mom.2": ["agent", "There is no notice, ma'am."],
  "nevada.agent.mom.3": ["mom", "I can see all four corners of it."],
  "nevada.agent.mom.4": ["agent", "I can neither confirm nor deny a corner."],
  "nevada.agent.bigsis.1": ["bigsis", "Under what authority is this area closed?"],
  "nevada.agent.bigsis.2": ["agent", "I can neither confirm nor deny that it is an area."],
  "nevada.agent.bigsis.3": ["bigsis", "It has a fence."],
  "nevada.agent.bigsis.4": ["agent", "I can neither confirm nor deny the fence."],
  "nevada.agent.lil.1": ["lilsis", "Why is your tie gray?"],
  "nevada.agent.lil.2": ["agent", "Move along, little girl."],
  "nevada.agent.lil.3": ["lilsis", "Is your car gray? Is your DOG gray? Do you have a dog?"],
  "nevada.agent.lil.4": ["agent", "I can neither confirm nor deny a dog."],
  "nevada.agent.lil.5": ["lilsis", "What's his NAME? Why are you standing there? Is it your turn? Who had the turn before you? Do you get a snack?"],
  "nevada.agent.lil.6": ["agent", "...Sir? It's me. I have a situation. No, sir. She is about seven."],
  "nevada.agent.lil.7": ["lilsis", "Who are you talking to? Is it your mommy? Can I say hi?"],
  "nevada.agent.lil.8": ["bigsis", "'It was,' she noted, 'the finest interrogation she had ever witnessed.'"],
  "nevada.agent.busy": ["agent", "Sir, now she wants to know whose side the SUN is on. ...No, sir. I didn't have an answer either."],
  "nevada.agent.again.1": ["lilsis", "Why is the sky? Not why is it BLUE. Why IS it?"],
  "nevada.agent.again.2": ["agent", "...We are going to need a bigger department."],
  "nevada.agent.coin.1": ["agent", "I can neither confirm nor deny that that is a coin."],
  "nevada.agent.coin.2": ["agent", "If it were a coin, I would have to file a report. So it is not a coin."],

  "nevada.notice.blocked.mom": ["mom", "The gentleman is standing exactly in front of it. One admires the precision."],
  "nevada.notice.blocked.bigsis": ["bigsis", "I can read 'AREA CLOSED'. The small print is behind his jacket. That is not enough to work with."],
  "nevada.notice.blocked.lilsis": ["lilsis", "The gray man is in the WAY. I could ask him to move. I could ask him a LOT of things."],
  "nevada.notice.mom.1": ["mom", "'Area closed. Elevated radiation levels. Sectors 44 and 2560 sealed until further notice.'"],
  "nevada.notice.mom.2": ["mom", "Sectors. As though the desert had been numbered. Your sister should see this."],
  "nevada.notice.lilsis": ["lilsis", "It says... A, R, E, A. And a yellow spinny flower. 'Radiator levels.' That's BAD, right?"],
  "nevada.notice.big.1": ["bigsis", "'Elevated radiation levels.' In Nevada, people will believe that. Fun fact: atomic bombs were tested out here from 1951 until 1992."],
  "nevada.notice.big.2": ["bigsis", "Which makes it a very good excuse. But look at the sectors. Forty-four. Twenty-five sixty."],
  "nevada.notice.big.3": ["bigsis", "Nobody numbers sectors like that. Those aren't places, Mother. I think those are years."],
  "nevada.notice.again": ["bigsis", "Sector 44. Sector 2560. Years. I am almost certain. 'Almost' is the part I don't like."],

  // ---------- the coin ----------
  "nevada.coin.read.1": ["bigsis", "Mother. This is a Roman denarius. And that is Julius Caesar."],
  "nevada.coin.read.2": ["bigsis", "Fun fact: in 44 B.C., coins were struck in Rome with Caesar's own portrait. While he was alive."],
  "nevada.coin.read.3": ["bigsis", "And it isn't two thousand years old. Look at the edges. It is NEW. It has hardly been in a pocket."],
  "nevada.coin.read.4": ["mom", "A new coin, from 44 B.C., that fell out of the sky. In Nevada."],
  "nevada.coin.lilsis": ["lilsis", "A money! With a grumpy man on it. Can I buy a lemonade with it?"],
  "nevada.coin.mom": ["mom", "Thank you, darling. I will keep it in my handbag, with everything else that matters."],
  "nevada.connect": ["bigsis", "Sector 44. A new coin from 44 B.C. It is the same forty-four. The holes don't go to places. They go to YEARS."],

  // ---------- the gate: where the tracks stop. Nothing to see but glass; and a hum ----------
  "nevada.tracks.look.mom": ["mom", "Tire tracks. They run out from under that fence and they simply... stop. At a patch of sand that has turned to glass."],
  "nevada.tracks.look.bigsis": ["bigsis", "It takes a furnace to turn sand into glass. Something here was very hot, very briefly."],
  "nevada.tracks.look.lilsis": ["lilsis", "The ground is SHINY. And it hums. Like a bee in a jar, but there's no bee. And no jar."],
  "nevada.tracks.early.mom": ["mom", "Not yet, darlings. I would like to understand it before any of us stands on it."],
  "nevada.tracks.early.bigsis": ["bigsis", "I have a theory. A theory is not a fact until I can footnote it."],
  "nevada.tracks.early.lilsis": ["lilsis", "Can I jump on it? ...Mommy's doing the eyebrow. That's a no."],
  // Going there once the coin and the notice are both read: each of them listens, and remembers the old man's flash.
  "nevada.hum.mom.1": ["mom", "It hums, darlings. Very quietly, like your father when he is lost and will not say so."],
  "nevada.hum.mom.2": ["mom", "The gentleman said a flash of low sun fell just here. I wonder what we have that flashes."],
  "nevada.hum.bigsis.1": ["bigsis", "It hums. Right here, over the glass, where there is nothing at all to hum."],
  "nevada.hum.bigsis.2": ["bigsis", "A flash of low sun fell here, and the sky opened. That is his whole story. So: we need a flash."],
  "nevada.hum.lilsis.1": ["lilsis", "It HUMS! Right THERE! There's nothing there and it HUMS!"],
  "nevada.hum.lilsis.2": ["lilsis", "The wizard said the car went FLASH and the sky went OPEN. I want to do a flash!"],
  // The coin, held up in the low sun, by whichever of them has it.
  "nevada.gate.1": ["bigsis", "The tracks don't turn. They don't skid. They just stop."],
  "nevada.flash.mom": ["mom", "Stand back a little, darlings. I am about to do something your father would think of."],
  "nevada.flash.bigsis": ["bigsis", "A low sun. A new coin. And an old man's story. This is called an experiment."],
  "nevada.flash.lilsis": ["lilsis", "My turn! I'm gonna do a FLASH! Like the car did! Everybody WATCH!"],
  // The door is open: the size of the coin. What comes through it is small, and settles nothing.
  "nevada.door.1": ["lilsis", "A HOLE! In the AIR! And it's LITTLE! It's littler than ME!"],
  "nevada.door.2": ["bigsis", "'The air,' she noted, 'now had a hole in it. A hole exactly the size of the coin.'"],
  "nevada.door.3": ["lilsis", "It's a DIFFERENT sunny in there! And it smells like SAUSAGES!"],
  "nevada.door.4": ["mom", "Sausages. She is quite right. And bread, and woodsmoke. And I believe I can hear chickens."],
  "nevada.door.5": ["bigsis", "It is morning in there, too. I do not think it is THIS morning."],
  "nevada.door.6": ["mom", "Then which morning, darling?"],
  "nevada.gate.2": ["bigsis", "Sector 44: forty-four B.C. The year Julius Caesar was killed, on the Ides of March."],
  "nevada.gate.2b": ["bigsis", "Sector 2560: twenty-five sixty B.C. About when the Great Pyramid was finished."],
  "nevada.gate.3": ["bigsis", "They didn't crash, Mother. They didn't go anywhere. They went some WHEN."],
  "nevada.gate.4": ["lilsis", "I TOLD you! Daddy's not lost! Daddy's EARLY!"],
  "nevada.gate.5": ["bigsis", "...More than four thousand years early. She was right. I need to sit down."],
  "nevada.gate.6": ["mom", "Then we know where they are. And we have a door. It is only a little small."],
  "nevada.gate.7": ["mom", "Girls. We are going to go and bring them home."],

  // ---------- the rest of the lot ----------
  "nevada.car.look.mom": ["mom", "My car. It has never once taken a shortcut. It is the only vehicle in this family still in this century."],
  "nevada.car.look.bigsis": ["bigsis", "Mom's car. She parked it parallel to nothing. Perfectly."],
  "nevada.car.look.lilsis": ["lilsis", "I get the front seat on the way home. I called it. I called it in the DRIVEWAY."],
  "nevada.shack.mom": ["mom", "'Last Stop.' I do hope that is geography and not a prediction."],
  "nevada.shack.bigsis": ["bigsis", "A building held together by paint and optimism. Mostly optimism."],
  "nevada.shack.lilsis": ["lilsis", "They sell ROCKS. You can just FIND rocks. This is the best shop ever."],
  "nevada.pump.mom": ["mom", "A gas pump with no gas in it. There is a great deal of that about."],
  "nevada.pump.bigsis": ["bigsis", "'The pump,' she noted, 'had not served a customer in her lifetime. Or, by the look of it, in her mother's.'"],
  "nevada.pump.lilsis": ["lilsis", "It has a ball on its head. Like a lollipop for cars."],
  "nevada.stand.mom": ["mom", "'Lemonade, one dollar. Rocks, two dollars. Stories extra.' An honest price list."],
  "nevada.stand.bigsis": ["bigsis", "Quartz, sandstone, and one that is just a rock. I respect the honesty."],
  "nevada.stand.lilsis": ["lilsis", "Lemonade! Mommy! LEMONADE! ...Please."],
  "nevada.fence.mom": ["mom", "A fence, put up in a hurry by people who were not expecting visitors."],
  "nevada.fence.bigsis": ["bigsis", "The posts are new, and the concrete around them is still dark. This fence went up yesterday."],
  "nevada.fence.lilsis": ["lilsis", "I could fit under that. ...I'm just SAYING."],

  // ---------- what they say to each other ----------
  "nevada.talk.mom.bigsis.1a": ["mom", "What do you make of it, darling?"],
  "nevada.talk.mom.bigsis.1b": ["bigsis", "It is too tidy. Real accidents are messy. This one has a fence and a sign."],
  "nevada.talk.mom.bigsis.2a": ["mom", "Two books in the car, darling, and you have not opened either. I am almost concerned."],
  "nevada.talk.mom.bigsis.2b": ["bigsis", "This is better than either of them. Do not tell them."],
  "nevada.talk.mom.bigsis.2c": ["mom", "Your secret is safe, darling."],
  "nevada.talk.mom.bigsis.coin.a": ["mom", "The gentleman gave me a coin. I would like your opinion of it."],
  "nevada.talk.mom.bigsis.coin.b": ["bigsis", "Then hand it over, Mother. I can't footnote what I can't hold."],
  "nevada.talk.mom.lilsis.1a": ["mom", "Drink your lemonade slowly, sweetheart."],
  "nevada.talk.mom.lilsis.1b": ["lilsis", "I AM drinking it slowly. I'm drinking it slowly really FAST."],
  "nevada.talk.mom.lilsis.2a": ["lilsis", "Mommy, is Daddy in trouble?"],
  "nevada.talk.mom.lilsis.2b": ["mom", "A little, sweetheart. But only with me, and only once he is home."],
  "nevada.talk.mom.lilsis.gray.a": ["mom", "That gentleman in gray will not move for me."],
  "nevada.talk.mom.lilsis.gray.b": ["lilsis", "Did you ask him enough times? You have to ask a LOT of times."],
  "nevada.talk.bigsis.mom.1a": ["bigsis", "For the record: I am not frightened. I am gathering data."],
  "nevada.talk.bigsis.mom.1b": ["mom", "Gather it close to me, please."],
  "nevada.talk.bigsis.mom.2a": ["bigsis", "Mom. If I turn out to be right about this, may I say so?"],
  "nevada.talk.bigsis.mom.2b": ["mom", "Once, darling. Graciously."],
  "nevada.talk.bigsis.mom.2c": ["bigsis", "...I'll practice."],
  "nevada.talk.bigsis.lilsis.2a": ["bigsis", "Stay where I can see you."],
  "nevada.talk.bigsis.lilsis.2b": ["lilsis", "You stay where I can see YOU. I'm the one with the boots."],
  "nevada.talk.bigsis.lilsis.gray.a": ["bigsis", "I need that man to look somewhere else for sixty seconds."],
  "nevada.talk.bigsis.lilsis.gray.b": ["lilsis", "I can do sixty HOURS."],
  "nevada.talk.bigsis.lilsis.1a": ["lilsis", "What's radiator levels?"],
  "nevada.talk.bigsis.lilsis.1b": ["bigsis", "Radiation. It's a kind of energy you can't see."],
  "nevada.talk.bigsis.lilsis.1c": ["lilsis", "Like me when I hide?"],
  "nevada.talk.bigsis.lilsis.1d": ["bigsis", "No. You are extremely visible. And audible."],
  "nevada.talk.lilsis.mom.1a": ["lilsis", "Mommy, the old man has a beard like Santa. Is he Santa on vacation?"],
  "nevada.talk.lilsis.mom.1b": ["mom", "If he is, darling, we have been very good this year."],
  "nevada.talk.lilsis.mom.2a": ["lilsis", "Mommy, when we find Daddy, can I tell him I fixed the internet?"],
  "nevada.talk.lilsis.mom.2b": ["mom", "You may tell him first, before anybody says anything else at all."],
  "nevada.talk.lilsis.mom.2c": ["lilsis", "Even before 'hi'?"],
  "nevada.talk.lilsis.bigsis.2a": ["lilsis", "Are you scared?"],
  "nevada.talk.lilsis.bigsis.2b": ["bigsis", "No. ...A little. Hold my hand. It is for your sake, obviously."],
  "nevada.talk.lilsis.bigsis.2c": ["lilsis", "I'm holding it MIGHTILY."],
  "nevada.talk.lilsis.bigsis.1a": ["lilsis", "I'm small but I'm mighty."],
  "nevada.talk.lilsis.bigsis.1b": ["bigsis", "You are small but you are LOUD. It is a different thing."],
  "nevada.talk.lilsis.bigsis.1c": ["lilsis", "It's the SAME thing."],


  // ---------- hints: one from each of them for every puzzle ----------
  "hint.nevada.witness.mom": ["mom", "The gentleman in the lawn chair has watched this road for forty years. Nobody has asked him nicely."],
  "hint.nevada.witness.bigsis": ["bigsis", "The old man is a witness, and he doesn't care for my questions. Mom could get a statue to talk."],
  "hint.nevada.witness.lilsis": ["lilsis", "The wizard man won't tell ME. He wants a dollar. Mommy has dollars AND manners."],
  "hint.nevada.coin.mom": ["mom", "I have a silver coin I cannot read. I should hand it to the one of us who can."],
  "hint.nevada.coin.bigsis": ["bigsis", "Mom is carrying a coin that fell out of the sky. I need to see it. In my own hands."],
  "hint.nevada.coin.lilsis": ["lilsis", "Mommy got a shiny money from the wizard. My sister knows about olden-days stuff."],
  "hint.nevada.distract.lilsis": ["lilsis", "The gray man is standing in front of the sign. I have SO many questions for him."],
  "hint.nevada.distract.mom": ["mom", "That man will not move for courtesy. He has not yet met your little sister."],
  "hint.nevada.distract.bigsis": ["bigsis", "He can deflect one question. Can he deflect two hundred? I know someone who has two hundred."],
  "hint.nevada.notice.bigsis": ["bigsis", "The man in gray has his hands full. Now I can read that notice properly."],
  "hint.nevada.notice.mom": ["mom", "The notice is free at last. Your sister should be the one to read it. She reads between the lines."],
  "hint.nevada.notice.lilsis": ["lilsis", "I got the gray man out of the way! Somebody who can read fast should go and read!"],
  "hint.nevada.tracks.mom": ["mom", "A flash of low sun opened the sky where the tracks stop. We have a low sun, and a very new coin."],
  "hint.nevada.tracks.bigsis": ["bigsis", "A flash of sun opened it once. The sun is low again, and the coin is new enough to flash. Where the tracks stop."],
  "hint.nevada.tracks.lilsis": ["lilsis", "The shiny money can do a FLASH! Like the car did! At the hummy place, where the car tracks stop!"],
};
